name = "mi2tw"
main = "src/index.tsx"
compatibility_date = "2022-10-10"
kv_namespaces = [
  { binding = "mi2tw_Auth", id = "b0d8851ca21040a4b06ff8ee470a9fd4" },
  { binding = "db", id = "3ffe1701-ea44-482f-8d3f-0d51e22b22e2" },
]

[vars]
twitter_client_id = "SHd2eXJIajBZQ25Cb3BZclYxZzI6MTpjaQ"
# twitter_client_secret = "<secret>"
